services:
  - type: web
    name: course-report-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python course_report_app/server.py
    autoDeployTrigger: commit
    healthCheckPath: /
